// v6.3.1820
(function(h,l,N,E,O,u,t,x,ga,ha,ia,y,U,F,ja,z,ka,la){function m(a,b,c,d){return function(){a.call(b,c,d)}}function B(a){return"object"==typeof a}function za(){for(var a=32,b="";a--;)b+=(0|16*O.random()).toString(16);return b}function A(a,b,c,d){var e;(e=a.addEventListener)?e.call(a,b,c,0):a.attachEvent(d||"on"+b,c)}function ma(){return N&&"preview"==N.loadPurpose}function G(a,b){for(var c in a)a.hasOwnProperty(c)&&a[c]!==n&&b(a[c],c)}function Aa(a){var b=(typeof a).charAt(0);return"[object Array]"==
V.call(a)?"a":"[object Date]"==V.call(a)?"d":b}function H(a,b){var c=[];G(a,function(a,e){c.push(ga(e)+"="+ga(b?Aa(a)+("[object Date]"==V.call(a)?+a:B(a)&&a?H(a,b):a):a))});return c.join("&")}function I(a,b){if(!a)throw Error(b);}function Ba(a){P[na]=a;return na++}function oa(){var a=h.olark;a&&a("api.boot.onIdentityReady",function(a,c,d){J=a;W=c;X=d})}function Q(a,b){function c(a){return"expires="+(new u(a)).toGMTString()+";"}var d="path=/;",e=a.g(6);e&&(d+="domain="+e+";");return{m:function(e,q){a.g(1,
1)&&(l.cookie=e+"="+q+";"+c(+new u+(b?6E10:6E4))+d)},A:function(b){if(a.g(1,1))return(l.cookie.match("(^|;)\\s*"+b+"=([^;]*)")||[])[2]||n},ca:function(a){l.cookie=a+"=;"+c(0)+d}}}function K(a){function b(){var a=d[z];a&&(d[z]=a[y](":_GS_:")[0])}var c;if(K[a])return K[a];var d=h.top;K[a]=c=function(){b();d[z]=(d[z]||"")+":_GS_:"+[a,c.f,c.I]};try{var e=d[z]||"";if(-1!=e[la](":_GS_:")){var f=e[y](":_GS_:")[1][y](",");f[0]==a&&(c.f=f[1]||"",c.I=f[2]||"")}b()}catch(q){d={}}return c}function pa(a){var b=
l[ka]("head")[0],c=l[ia]("script");c.src=a;b.appendChild(c);return function(){c&&b.removeChild(c);c=null}}function R(a){var b=v.c;b||(b=v.c=function(a){b.q.push(a)},b.q=[]);b(a)}function C(a){function b(b){f.m(d,q.f=b?"":[Y,548*k.D+2019,379*k.B+4621,+new u].join(":"));a.s(11,b?0:Y)}function c(){h&&"-"!==h?(f.m(e,h+(m?"|"+m:"")),R(["i",a.b,h,m])):(f.m(e,""),R(["u",a.b]))}var d="gs_u_"+a.b,e="gs_v_"+a.b,f=Q(a,1),q=K(a.b),g=(f.A(d)||q.f||"")[y](/(?::|%3A)/),p=1,Y=a.g(11,g[0])||(p=0,za()),Ca=((g[1]||
2019)-2019)/548,l=((g[2]||4621)-4621)/379,g=(g[3]||0)/1E3,h=a.g(13),m=a.g(14),k;k={f:Y,C:h,D:Ca,B:l,ia:~~g,pa:p,ga:function(a,c){k.B+=+a;k.D+=+c;b()},X:function(a){h=k.C=a;c()},qa:b,na:function(){var b=f.A("gs_p_"+a.b)||q.I;f.ca("gs_p_"+a.b);return a.i!==n?a.i:b},M:m,ra:function(a){I(/^[0-9a-f]{64}$/.test(a),"Invalid auth signature");m=k.M=a;c()}};c();return k}function S(a,b,c,d,e){var f=m,q=t(function(){f();Z=(Z+1)%aa[F];c.et&&(c.et=0);c.rt=1;--e&&S(a,b,c,d,e)},1E4),g=C(a);c.cb=Ba(function(a,b){d(a,
b);f();x(q)});c.a=a.b;c.au=g.M;c.id=g.f;c.cid=g.C;c.tv=ha;g=b+"?"+H(c);f=pa((Da?"https":"http")+"://"+aa[Z]+".gosquared.com/"+g)}function qa(a,b,c){var d=l[ia]("a");d.href=b||h.location.href;b=d.href;a.g(7,1)||(b=b[U](/\?[^#]*/,""));a.g(8)||(b=b[U](/#.*$/,""));return{sa:b,t:c!==n?c:l.title,U:/^file:/.test(b)||/\/\/localhost[\/:]/.test(b+"/"),T:/fb_xd_(bust|fragment)/.test(b)}}function ra(a){var b;if(a.L){var c=qa(a);!a.g(9)&&c.U||c.T||ma()||(b=H(a.h,1))&&S(a,"prop",{cp:b},m,5)}else t(function(){ra(a)},
100)}function sa(a,b,c){var d=a.h=a.h||{};I(b||B(c),"Not an object");b?d[b]=c:d=a.h=c;!a.W&&a.L&&(a.W=t(function(){ra(a);a.W=0},100))}function Ea(){var a=0,b=0,c;E&&(a=E.width,b=E.height);c=(c=h.orientation)&&(c+360)%180;return{K:c?b:a,J:c?a:b,aa:E&&E.colorDepth||"-",ha:N.language||N.browserLanguage||"-",ba:l.characterSet||l.charSet||"-",da:h.devicePixelRatio||1,ja:(new u).getTimezoneOffset()}}function ba(){function a(a){return h["inner"+a]||c&&c[e="client"+a]||d&&d[e]}function b(a){return O.max(d[e=
"scroll"+a]|0,c[e]|0,d[e="offset"+a]|0,c[e]|0,d[e="client"+a]|0,c[e]|0)}var c=l.documentElement,d=l.body||c,e;return{Z:a("Width"),Y:a("Height"),R:b("Width"),P:b("Height"),o:h.pageXOffset||c&&c.scrollLeft||0,u:h.pageYOffset||c&&c.scrollTop||0}}function ta(a){a.j&&(a.j=0,a.w=new u-a.F+(a.w||0))}function ca(a){x(a.ka);a.ka=t(m(ta,0,a),15E3);a.j||(a.j=1,a.F=new u)}function Fa(a){var b=a.w,c=new u;a.j&&(b+=c-a.F,a.F=c);a.w=0;return b}function Ga(a){ca(a);var b=ba();b.u>a.H&&(a.H=b.u);b.o>a.G&&(a.G=b.o)}
function Ha(a){var b=m(ca,0,a);A(l,"mousemove",b);A(l,"keydown",b);A(h,"scroll",m(Ga,0,a));A(l,"focus",b,"focusin");A(l,"blur",m(ta,0,a),"focusout")}function Ia(a){a=a.g(10,l.referrer);var b;!a||/^(chrome|about|file):/.test(a)||/^\[.*\]$/.test(a)?a="-":b=a[U](/^.*?\/\//,"")[la](location.host);return{S:+(0<=b&&8>=b),oa:a}}function T(a,b,c,d){if(a.i!==n){if(!c){var e=ba();c={vw:e.Z,vh:e.Y,dw:e.R,dh:e.P,st:e.u,sl:e.o,mst:a.H,msl:a.G}}c.i=a.i;c.e=b;c.et=Fa(a);r&&(c.bc=1);a.V&&J&&(a.V=0,c.o_si=J,c.o_vi=
W,c.o_ci=X);S(a,"ping",c,function(){d&&d();x(a.l);a.l=t(m(T,0,a),[7E3,12E3][a.ma++]||17500+5E3*O.random())},5)}else t(function(){T(a,b,c,d)},5E3)}function Ja(a){if(a.i!==n){var b=Q(a);a.g(1,1)?b.m("gs_p_"+a.b,a.i):(b=K(a.b),b.I=a.i,b())}}function da(a,b,c){I(a,"Event name is required");b&&b.call&&(c=b,b=n);if(b===""+b||b===+b)b={caption:b};a={gs_evt_name:a,d:H(b||{},1)};T(this,"event",a,c)}function ea(a,b,c){a&&a.call&&(c=a,a=n);b&&b.call&&(c=b,b=n);var d=this,e=qa(d,a,b),f=Ia(d),q=d.i===n&&!f.S;
b=d.L=C(d);var g=Ea(),p=ba(),k=d.g(5);b.ga(1,q);x(d.l);d.w=0;d.j=0;ca(d);!d.g(9)&&e.U||e.T||ma()||g.K&&g.J&&10>g.K&&10>g.J||(d.H=p.u,d.G=p.o,e={cs:g.ba,cd:g.aa,la:g.ha,sw:g.K,sh:g.J,dp:g.da,pu:e.sa,pt:e.t||"-",ri:f.S,ru:f.oa,re:b.pa,vi:b.D,pv:b.B,lv:b.ia,vw:p.Z,vh:p.Y,dw:p.R,dh:p.P,st:p.u,sl:p.o,un:d.g(3),pp:b.na(),ec:k,aip:d.g(2)?1:n,tz:g.ja},d.h&&(e.cp=H(d.h,1)),d.ea||!1===d.g(15)||(e.rc=1,d.ea=1),r&&(d.uid=b.f,e.bc=1),J?(e.o_si=J,e.o_vi=W,e.o_ci=X):d.V=1,d.ma=0,S(d,"pv",e,function(a,b){a!==n&&
(d.i=a,x(d.l),d.l=t(m(T,0,d),5E3),c&&c());if(b){R(b);var e=v.c;e.c||(e.c=[2,d.b,d.g(15),d.g(11),d.g(6)]);var e=(d.g(15)||{}).js||"https://js.gs-chat.com/chat.js",f=b[0];ua||(ua=1,pa(e+(f?"?"+f.v:"")))}},5),d.i!==n?a!==n&&(d.i=n):(t(m(Ha,0,d),500),A(h,"beforeunload",m(Ja,0,d))))}function va(a){var b="gs_v_"+a,c=this,d=[];d[12]=c.b=a;c.s=function(a,b,e){4==a&&(sa(c,e,b),b&&!c.N&&(e=b.id,b=b.email,!e&&b&&(e="email:"+b),e&&(c.N=e,C(c).X(e))),b=c.h);13==a&&(sa(c,"id",b),b=(c.N=b)||"-",C(c).X(b));14==a&&
C(c).ra(b);d[a]=b};c.g=function(a,e){function g(){var a=Q(c,1).A(b),d;/\|[0-9a-f]{32,64}/.test(a)&&(a=a[y]("|"),d=a.pop(),a=a.join("|"));return{$:d,C:a}}return a in d?d[a]:13==a?g().C||e:14==a?g().$||e:e};var e;c.fa=function(){e=t(m(ea,c),20)};c.O=function(){x(c.l);x(e)}}function fa(a,b,c){if(!a)for(a in k)return k[a];if(k[b||a])return k[b||a];a=k[b||a]=new va(a);c&&a.fa();return a}function D(a,b,c,d,e){b?a.call(k[b],c,d,e):G(k,function(b){a.call(b,c,d,e)})}function Ka(a,b,c,d){function e(a,b){b=
b||(B(a)?a:{});B(a)||(b[z]=a);I(b[z],"No Name");g.push(b);return h}function f(a){for(var b=0;b<a[F];)e(a[b++]);return h}function k(){D(function(){var a=Q(this,1),d="gs_t_"+this.b,e=a.A(d)||0;a.m(d,+new u);da.call(this,"_transaction",{id:b,pt:{ts:+e},i:g,d:c})},a)}!c&&B(b)&&(c=b,b=c.id);var g=[],h;d&&f(d);c&&c.track&&k();return h={id:b,addItem:e,addItems:f,track:k}}function La(a,b){!b&&B(a)&&(b=a,a=b.id,!a&&b.email&&(a="email:"+b.email));I(a,"ID or email required");this.s(13,a);b&&this.s(4,b)}function v(a,
b,c,d){if(a&&a.call)a();else if(/^GSN-.*-.$/.test(a))b!==""+b&&(c=b,b=0),fa(a,b,c||c===n);else if(P[a])P[a](b,c),delete P[a];else{var e=function(a,b,c){f?k[f].s(a,b,c):G(k,function(d){d.s(a,b,c)})};a=a[y](".");var f;1<a[F]&&(f=a.shift());a=a[0];var h={usecookies:1,anonymizeip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,trackparams:7,trackhash:8,tracklocal:9,referrer:10,visitorid:13,visitor:4,clientid:11,auth:14,props:4,properties:4,chat:15};if(/transaction$/i.test(a))return Ka(f,b,c,d);
if("get"==a)return c=h[(b+"")[ja]()]||b,f?d=k[f].g(c):G(k,function(a){d=a.g(c)}),d;"set"==a?(a=(b+"")[y]("."),b=a.shift(),e(h[b[ja]()]||b,c,a.join("."))):"track"==a?D(ea,f,b,c,d):"event"==a?D(da,f,b,c,d):"cancel"==a?D(function(){this.O()},f):"noCookies"==a?e(1,0):"anonymizeIP"==a?e(2,1):"tag"==a?e(3,b):"load"==a?b&&b():"auth"==a?e(14,b):"identify"==a?D(La,f,b,c,d):"alias"==a?e(13,b):"unidentify"==a?D(function(){this.g(13)&&(this.s(13),C(this).qa(1))}):"props"==a||"properties"==a?e(4,b):"chat"==a&&
R([b,c,d])}}function wa(a){v.apply({},a)}var n,L,M=h._gs||(L=1,function(){xa.push(arguments)}),xa=M.q||[];if(!M.v){var r=h.GoSquared,V=Object.prototype.toString,P={},na=0,J,W,X,aa=["data","data2"],Z=0|O.random()*aa[F],Da=/^https:/.test(location.href),ua,k={};if(r){G(r,function(a,b){"acct"==b?(fa(a,"_default",1),M(function(){function c(a){d[a.shift()].apply(d,a)}var d=r.DefaultTracker=k._default;if(b=r.q)for(;a=b.shift();)c(a);r.q={push:c};(b=r.load)&&b(d)})):"load"!=b&&"q"!=b&&M("set",b,a)});var w=
va.prototype;w.TrackView=ea;w.TrackEvent=da;w.Cancel=function(){this.O()};r.Tracker=fa;r.Cancel=m(v,0,"cancel")}h._gs=v;v.v=ha;for(M.q={push:wa};w=xa.shift();)wa(w);if(L){L=l[ka]("script");for(var w=L[F],ya;w--;)(ya=L[w].getAttribute("data-gs"))&&v(ya)}oa();A(h,"load",oa)}})(window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,encodeURIComponent,"6.3.1820","createElement","split","replace","length","toLowerCase","name","getElementsByTagName","indexOf");
